# Write a postgres service with just username password and database

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mobility_test
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data